DROP TABLE IF EXISTS DEVICE_CATEGORY;

CREATE TABLE DEVICE_CATEGORY(
  NAME VARCHAR(250) NOT NULL PRIMARY KEY
);

INSERT INTO DEVICE_CATEGORY VALUES 'Telewizor';
INSERT INTO DEVICE_CATEGORY VALUES 'Komputer';