DROP TABLE IF EXISTS DEVICE_CATEGORY;

CREATE TABLE DEVICE_CATEGORY(
  NAME VARCHAR(120) NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS DEVICE_COMMENT;

CREATE TABLE DEVICE_COMMENT(
  ID NUMBER NOT NULL PRIMARY KEY,
  CONTENT VARCHAR(500) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  MODIFICATION_DATE TIMESTAMP NOT NULL,
  DEVICE_ID NUMBER NOT NULL,
  FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID)
);

DROP TABLE IF EXISTS DEVICE_PARAMETER;

CREATE TABLE DEVICE_PARAMETER(
  ID NUMBER NOT NULL PRIMARY KEY,
  NAME VARCHAR(120) NOT NULL,
  VALUE VARCHAR(240) NOT NULL,
  DEVICE_ID NUMBER NOT NULL,
  FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID)
);

DROP TABLE IF EXISTS DEVICE;

CREATE TABLE DEVICE(
  ID NUMBER NOT NULL PRIMARY KEY,
  NAME VARCHAR(120) NOT NULL,
  IS_BROKEN NUMBER(1) NOT NULL,
  CATEGORY_NAME VARCHAR(120) NOT NULL,
  FOREIGN KEY (CATEGORY_NAME) REFERENCES DEVICE_CATEGORY(NAME)
);